using System.Collections.Generic;

namespace PofudukFilo.Core
{
    /// <summary>
    /// Turkish → English. <see cref="Exact"/> matches whole strings; <see cref="Templates"/> use
    /// {0}, {1}… for parts that are translated recursively (numbers, names). Keep keys identical
    /// to the Turkish in code/data — tools/verify/run.sh reports any player-facing string that
    /// neither table covers.
    /// </summary>
    public static class LocTableEn
    {
        public static readonly Dictionary<string, string> Exact = new()
        {
            // ---- Title, menu, common buttons
            ["POFUDUK"] = "FLUFFY",
            ["FİLO"] = "FLEET",
            ["Pofuduk Filo"] = "Fluffy Fleet",
            ["OYNA"] = "PLAY",
            ["Atölye"] = "Workshop",
            ["Hangar"] = "Hangar",
            ["Laboratuvar"] = "Lab",
            ["Silah Laboratuvarı"] = "Weapon Lab",
            ["Takımyıldız"] = "Constellation",
            ["Ayarlar"] = "Settings",
            ["Geri"] = "Back",
            ["Kapat"] = "Close",
            ["Açık"] = "On",
            ["Kapalı"] = "Off",
            ["Seç"] = "Select",
            ["Seçili"] = "Selected",
            ["Havuzda"] = "In pool",
            ["Aç"] = "Unlock",
            ["Sıfırla"] = "Reset",
            ["MAKS"] = "MAX",
            ["Bir yıldıza dokun."] = "Tap a star.",
            ["Tüm yıldız tozu iade edildi."] = "All stardust refunded.",

            // ---- Settings
            ["Ses efektleri"] = "Sound effects",
            ["Müzik"] = "Music",
            ["Titreşim"] = "Vibration",
            ["Ekran sarsıntısı"] = "Screen shake",
            ["Hasar sayıları"] = "Damage numbers",
            ["Dil"] = "Language",
            ["Türkçe"] = "Türkçe",
            ["English"] = "English",

            // ---- HUD, toasts
            ["Formasyon Temizlendi!"] = "Formation Cleared!",
            ["Sandık!"] = "Chest!",
            ["JACKPOT!"] = "JACKPOT!",
            ["ŞEKER"] = "SUGAR",
            ["HÜCUM!"] = "RUSH!",
            ["ŞEKER HÜCUMU!"] = "SUGAR RUSH!",
            ["Filo güçlendi!"] = "Fleet powered up!",
            ["ŞEKER!"] = "SUGAR!",
            ["ŞEKER HAZIR! Dokun!"] = "SUGAR READY! Tap!",
            ["UYARI!"] = "WARNING!",

            // ---- Level-up
            ["Seviye Atladın!"] = "Level Up!",
            ["Yeniden Çek"] = "Reroll",
            ["Yasakla"] = "Banish",
            ["Kart seç…"] = "Pick a card…",
            ["YENİ!"] = "NEW!",
            ["NADİR"] = "RARE",
            ["EPİK"] = "EPIC",
            ["EFSANE"] = "LEGENDARY",
            ["YAYGIN"] = "COMMON",
            ["Şeker Molası"] = "Sugar Break",
            ["Can +30, can doluysa +50 altın"] = "+30 HP, or +50 gold at full HP",
            ["hasar"] = "damage",
            ["atış hızı"] = "fire rate",
            ["alan"] = "area",
            ["süre"] = "duration",
            ["mermi hızı"] = "projectile speed",
            ["kritik şansı"] = "crit chance",
            ["maks. can"] = "max HP",
            ["mıknatıs"] = "magnet",
            ["şans"] = "luck",
            ["altın"] = "gold",

            // ---- Pause, death, run end
            ["Mola"] = "Paused",
            ["Devam Et"] = "Resume",
            ["Koşuyu Bitir"] = "End Run",
            ["Pıtır düştü!"] = "Knocked out!",
            ["Diril"] = "Revive",
            ["Reklam İzle, Devam Et"] = "Watch Ad to Continue",
            ["Bitir"] = "Give Up",
            ["Tekrar Oyna"] = "Play Again",
            ["Geliştir"] = "Upgrade",
            ["Geliştir  !"] = "Upgrade  !",
            ["Sonsuz Mod'a Devam (+%50 altın)"] = "Continue in Endless (+50% gold)",
            ["Sonsuz Mod bitti!"] = "Endless run over!",
            ["Zafer!"] = "Victory!",
            ["Az kaldı!"] = "So close!",
            ["Altını 2 Katla (Reklam)"] = "Double Gold (Ad)",
            ["Altın 2 katına çıktı!"] = "Gold doubled!",

            // ---- Weapons
            ["Tüy Blaster"] = "Feather Blaster",
            ["Yumurta Havanı"] = "Egg Mortar",
            ["Yıldız Bumerang"] = "Star Boomerang",
            ["Sakız Balonu"] = "Bubble Orbit",
            ["Kıvılcım Kedi"] = "Spark Cat",
            ["Gökkuşağı Prizma Işını"] = "Rainbow Prism Beam",
            ["Süpernova Omleti"] = "Supernova Omelette",
            ["Galaksi Girdabı"] = "Galaxy Vortex",
            ["Sakız Gezegen Halkaları"] = "Gum Planet Rings",
            ["Fırtına Kedisi Tanrıçası"] = "Storm Cat Goddess",
            ["Gökkuşağı Fırtınası"] = "Rainbow Storm",
            ["Kozmik Kahvaltı"] = "Cosmic Breakfast",
            ["Şeker Kalkanı Galaksisi"] = "Candy Shield Galaxy",
            ["Kırılan gökkuşağı lazeri"] = "A refracting rainbow laser",
            ["2 paralel tüy, hızlı atış"] = "2 parallel feathers, rapid fire",
            ["3 paralel tüy, daha hızlı"] = "3 parallel feathers, faster",
            ["3 tüy, hafif yelpaze"] = "3 feathers in a light fan",
            ["Hasar +%30, tüyler 1 düşmanı deler"] = "+30% damage, feathers pierce 1 enemy",
            ["5 tüy; her 5. atış dev tüy (3×)"] = "5 feathers; every 5th shot is a giant feather (3×)",
            ["Her 5 atışta ekranı kaplayan omlet dalgası"] = "Every 5 shots, a screen-wide omelette wave",
            ["Patlayan yumurta"] = "Exploding egg",
            ["2 yumurta"] = "2 eggs",
            ["Patlama alanı +%40"] = "+40% blast area",
            ["Patlamadan 2 mini civciv çıkar"] = "Blasts release 2 mini chicks",
            ["4 yumurta, daha sık"] = "4 eggs, more often",
            ["Düşmanları çeken galaksi sarmalı"] = "A galaxy spiral that pulls enemies in",
            ["Gidip dönen yıldız"] = "A star that flies out and back",
            ["2 yıldız"] = "2 stars",
            ["Menzil +%30, dönüşte 1.5× hasar"] = "+30% range, 1.5× damage on the return",
            ["3 yıldız"] = "3 stars",
            ["Dönen yıldızlar gemi etrafında tur atar"] = "Returning stars circle the ship",
            ["Emen, yapıştıran ve biçen 3 halka"] = "3 rings that absorb, stick and slice",
            ["Etrafında dönen 2 balon"] = "2 bubbles orbit you",
            ["3 balon"] = "3 bubbles",
            ["Balonlar düşman mermisi yutar"] = "Bubbles swallow enemy bullets",
            ["4 balon, daha geniş yörünge"] = "4 bubbles, wider orbit",
            ["Mermi yutan balon patlar"] = "A bubble that swallows a bullet bursts",
            ["Yıldırım yağmuru ve elektrikli papatyalar"] = "Lightning rain and electric daisies",
            ["Zincirleme şimşek (2 sekme)"] = "Chain lightning (2 bounces)",
            ["4 sekme"] = "4 bounces",
            ["Vurulan düşman sersemler"] = "Hit enemies are stunned",
            ["İkinci kedi"] = "A second cat",
            ["Sekmelerde hasar azalmaz"] = "No damage falloff on bounces",

            // ---- Passives
            ["Kristal Gözlük"] = "Crystal Glasses",
            ["Sıcak Tava"] = "Hot Pan",
            ["Ay Tozu"] = "Moon Dust",
            ["Esnek Sakız"] = "Stretchy Gum",
            ["Pil Tasması"] = "Battery Collar",
            ["Havuç Kalkan"] = "Carrot Shield",
            ["Mıknatıs Kulak"] = "Magnet Ears",
            ["Şans Yoncası"] = "Lucky Clover",

            // ---- Characters
            ["Pıtır"] = "Pip",
            ["Cıvık"] = "Chirpy",
            ["Mırnav"] = "Purrl",
            ["Balonbaş"] = "Bubbles",
            ["Yıldızpati"] = "Starpaw",
            ["Gökkuşağı Pıtır"] = "Rainbow Pip",
            ["Tavşan. Her 10 seviyede +1 kart seçeneği."] = "Bunny. +1 card choice every 10 levels.",
            ["Civciv. Patlamalar %20 büyük, can -%10."] = "Chick. Blasts 20% bigger, -10% HP.",
            ["Kedi. Sersemletme süresi 2 kat."] = "Cat. Stuns last twice as long.",
            ["Hamster. Yuttuğu her mermi 1 can."] = "Hamster. Every swallowed bullet heals 1 HP.",
            ["Tilki. Her evrim +%15 hasar."] = "Fox. +15% damage per evolution.",
            ["Gizli. Her koşu rastgele bir pasifle başlar."] = "Secret. Starts every run with a random passive.",

            // ---- Workshop
            ["Can"] = "Health",
            ["Hasar"] = "Damage",
            ["Atış Hızı"] = "Fire Rate",
            ["Mıknatıs"] = "Magnet",
            ["Zırh"] = "Armor",
            ["Şans"] = "Luck",
            ["Tecrübe"] = "Experience",
            ["Diriliş"] = "Revive",

            // ---- Constellation
            ["Kıvılcım"] = "Spark",
            ["Keskin Göz"] = "Sharp Eye",
            ["Alev"] = "Flame",
            ["Çevik Pati"] = "Nimble Paw",
            ["Geniş Kanat"] = "Wide Wing",
            ["Yıldız Ateşi"] = "Starfire",
            ["Rüzgâr"] = "Wind",
            ["Uzun Kuyruk"] = "Long Tail",
            ["Süpernova"] = "Supernova",
            ["Evrim Yıldızı"] = "Evolution Star",
            ["Evrim sandığı +1 pasif seviyesi verir"] = "Evolution chests grant +1 passive level",
            ["Pamuk"] = "Cotton",
            ["Kabuk"] = "Shell",
            ["Çekim"] = "Pull",
            ["Yastık"] = "Pillow",
            ["Kıl Payı"] = "Close Call",
            ["Kıl payı XP'si 2 kat"] = "Graze XP ×2",
            ["Kalp"] = "Heart",
            ["Anka"] = "Phoenix",
            ["Büyük Çekim"] = "Big Pull",
            ["Kale"] = "Fortress",
            ["Kese"] = "Pouch",
            ["Yonca"] = "Clover",
            ["Bilge"] = "Sage",
            ["Taç Avcısı"] = "Crown Hunter",
            ["Hazine"] = "Treasure",
            ["İkinci Şans"] = "Second Chance",
            ["Âlim"] = "Scholar",
            ["Seçici"] = "Picky",
            ["Define"] = "Hoard",
            ["Dördüncü Kart"] = "Fourth Card",
            ["Seviye atlamada 4 kart"] = "4 cards on level-up",

            // ---- Chapters and phases
            ["Şekerkamışı"] = "Candy Cane Lane",
            ["Jöle Nebulası"] = "Jelly Nebula",
            ["Kurabiye Kuşağı"] = "Cookie Belt",
            ["Mini-Boss: Jöle Kral!"] = "Mini-Boss: Jelly King!",
            ["Mini-Boss: Kurabiye Robot Ana!"] = "Mini-Boss: Cookie Mech Mama!",
            ["Final: Kraliçe Tavuk!"] = "Final: Queen Hen!",

            // ---- Ads
            ["Kilitli — açınca kart havuzuna girer"] = "Locked — unlocking adds it to the card pool",
            ["Sv. Atla"] = "Level Up",
            ["SONSUZ"] = "ENDLESS",
            ["ATEŞ GÜCÜ"] = "FIREPOWER",
            ["ATEŞ HIZI"] = "FIRE RATE",
            ["YENİ REKOR!"] = "NEW RECORD!",
            ["Reklam hazır değil, biraz sonra dene."] = "Ad not ready, try again soon."
        };

        public static readonly Dictionary<string, string> Templates = new()
        {
            ["Sv. {0}"] = "Lv. {0}",
            ["SONSUZ\nRekor {0}"] = "ENDLESS\nBest {0}",
            ["Rekor: {0}"] = "Best: {0}",
            ["{0}\nSv.{1}  ·  {2} altın"] = "{0}\nLv.{1}  ·  {2} gold",
            ["{0}\nSv.{1}  ·  MAKS"] = "{0}\nLv.{1}  ·  MAX",
            ["{0}  YENİ!"] = "{0}  NEW!",
            ["{0}  Sv.{1}"] = "{0}  Lv.{1}",
            ["Sv.{0}"] = "Lv.{0}",
            ["Seviye {0}!"] = "Level {0}!",
            ["Seviye {0}   ·   {1} düşman   ·   {2}"] = "Level {0}   ·   {1} enemies   ·   {2}",
            ["EVRİM! {0}"] = "EVOLVED! {0}",
            ["Yeniden Çek ({0})"] = "Reroll ({0})",
            ["Yasakla ({0})"] = "Banish ({0})",
            ["Diril ({0})"] = "Revive ({0})",
            ["Evrim anahtarı: {0}"] = "Evolution key: {0}",
            ["+%{0} {1}"] = "+{0}% {1}",
            ["+{0} altın"] = "+{0} gold",
            ["+{0} Yıldız Tozu"] = "+{0} Stardust",
            ["{0} altın   ·   {1} Yıldız Tozu"] = "{0} gold   ·   {1} Stardust",
            ["{0} altın"] = "{0} gold",
            ["{0} altın\n{1} toz"] = "{0} gold\n{1} dust",
            ["{0} toz"] = "{0} dust",
            ["{0} geliştirmesi hazır!"] = "{0} upgrade ready!",
            ["{0} için {1} altın kaldı"] = "{1} gold to {0}",
            ["Bölüm {0}"] = "Chapter {0}",
            ["Bölüm {0}  (kilitli)"] = "Chapter {0}  (locked)",
            ["Bölüm {0}'i bitir"] = "Clear Chapter {0}",
            ["Pilot: {0}"] = "Pilot: {0}",
            ["{0}  (silah)"] = "{0}  (weapon)",
            ["{0}  (pasif)"] = "{0}  (passive)",
            ["{0}  (açık)"] = "{0}  (owned)",
            ["{0}  {1}/{2}"] = "{0}  {1}/{2}",
            ["{0} KOMBO"] = "{0} COMBO",
            ["Filoya katıldı! ({0})"] = "Joined the fleet! ({0})",
            ["{0} + {1}"] = "{0} + {1}",
            ["<size={0}>{1}</size>"] = "<size={0}>{1}</size>",
            ["Ustalık {0}/{1}"] = "Mastery {0}/{1}",
            ["Pilot Sv. {0}/{1}  (+%{2} hasar ve can)"] = "Pilot Lv. {0}/{1}  (+{2}% damage and HP)",
            ["{0} — Dalga {1}"] = "{0} — Wave {1}",
            ["Dalga {0}: Kaos"] = "Wave {0}: Chaos",
            ["Dalga {0}"] = "Wave {0}",
            ["Alınan hasar -{0}"] = "Damage taken -{0}",
            ["Elitlerden +%{0} altın"] = "+{0}% gold from elites",
            ["+{0} diriliş"] = "+{0} revive",
            ["+{0} yeniden çek"] = "+{0} reroll",
            ["+{0} yasakla"] = "+{0} banish"
        };
    }
}
