using System.Collections.Generic;

namespace PofudukFilo.Core
{
    /// <summary>
    /// Turkish → English. <see cref="Exact"/> matches whole strings; <see cref="Templates"/> use
    /// {0}, {1}… for parts that are translated recursively (numbers, names). Keep keys identical
    /// to the Turkish in code/data — tools/verify/run.sh reports any player-facing string that
    /// neither table covers.
    /// </summary>
    public static class LocTableEn
    {
        public static readonly Dictionary<string, string> Exact = new()
        {
            // ---- Title, menu, common buttons
            ["POFUDUK"] = "FLUFFY",
            ["FİLO"] = "FLEET",
            ["Pofuduk Filo"] = "Fluffy Fleet",
            ["OYNA"] = "PLAY",
            ["Atölye"] = "Workshop",
            ["Hangar"] = "Hangar",
            ["Laboratuvar"] = "Lab",
            ["Silah Laboratuvarı"] = "Weapon Lab",
            ["Takımyıldız"] = "Constellation",
            ["Ayarlar"] = "Settings",
            ["Geri"] = "Back",
            ["Kapat"] = "Close",
            ["Açık"] = "On",
            ["Kapalı"] = "Off",
            ["Seç"] = "Select",
            ["Seçili"] = "Selected",
            ["Havuzda"] = "In pool",
            ["Aç"] = "Unlock",
            ["Sıfırla"] = "Reset",
            ["MAKS"] = "MAX",
            ["Bir yıldıza dokun."] = "Tap a star.",
            ["Tüm yıldız tozu iade edildi."] = "All stardust refunded.",

            // ---- Settings
            ["Ses efektleri"] = "Sound effects",
            ["Müzik"] = "Music",
            ["Titreşim"] = "Vibration",
            ["Ekran sarsıntısı"] = "Screen shake",
            ["Hasar sayıları"] = "Damage numbers",
            ["Dil"] = "Language",
            ["Türkçe"] = "Türkçe",
            ["English"] = "English",

            // ---- HUD, toasts
            ["Formasyon Temizlendi!"] = "Formation Cleared!",
            ["Sandık!"] = "Chest!",
            ["JACKPOT!"] = "JACKPOT!",
            ["ŞEKER"] = "SUGAR",
            ["HÜCUM!"] = "RUSH!",
            ["ŞEKER HÜCUMU!"] = "SUGAR RUSH!",
            ["Filo güçlendi!"] = "Fleet powered up!",
            ["ŞEKER!"] = "SUGAR!",
            ["ŞEKER HAZIR! Dokun!"] = "SUGAR READY! Tap!",
            ["UYARI!"] = "WARNING!",

            // ---- Level-up
            ["Seviye Atladın!"] = "Level Up!",
            ["Yeniden Çek"] = "Reroll",
            ["Yasakla"] = "Banish",
            ["Kart seç…"] = "Pick a card…",
            ["YENİ!"] = "NEW!",
            ["NADİR"] = "RARE",
            ["EPİK"] = "EPIC",
            ["EFSANE"] = "LEGENDARY",
            ["YAYGIN"] = "COMMON",
            ["Şeker Molası"] = "Sugar Break",
            ["Can +30, can doluysa +50 altın"] = "+30 HP, or +50 gold at full HP",
            ["hasar"] = "damage",
            ["atış hızı"] = "fire rate",
            ["alan"] = "area",
            ["süre"] = "duration",
            ["mermi hızı"] = "projectile speed",
            ["kritik şansı"] = "crit chance",
            ["maks. can"] = "max HP",
            ["mıknatıs"] = "magnet",
            ["şans"] = "luck",
            ["altın"] = "gold",

            // ---- Pause, death, run end
            ["Mola"] = "Paused",
            ["Devam Et"] = "Resume",
            ["Koşuyu Bitir"] = "End Run",
            ["Pıtır düştü!"] = "Knocked out!",
            ["Diril"] = "Revive",
            ["Reklam İzle, Devam Et"] = "Watch Ad to Continue",
            ["Bitir"] = "Give Up",
            ["Tekrar Oyna"] = "Play Again",
            ["Geliştir"] = "Upgrade",
            ["Geliştir  !"] = "Upgrade  !",
            ["Sonsuz Mod'a Devam (+%50 altın)"] = "Continue in Endless (+50% gold)",
            ["Sonsuz Mod bitti!"] = "Endless run over!",
            ["Zafer!"] = "Victory!",
            ["Az kaldı!"] = "So close!",
            ["Altını 2 Katla (Reklam)"] = "Double Gold (Ad)",
            ["Altın 2 katına çıktı!"] = "Gold doubled!",

            // ---- Weapons
            ["Tüy Blaster"] = "Feather Blaster",
            ["Yumurta Havanı"] = "Egg Mortar",
            ["Yıldız Bumerang"] = "Star Boomerang",
            ["Sakız Balonu"] = "Bubble Orbit",
            ["Kıvılcım Kedi"] = "Spark Cat",
            ["Gökkuşağı Prizma Işını"] = "Rainbow Prism Beam",
            ["Tüy Fırtınası"] = "Feather Storm",
            ["7 tüylük yelpaze, 2 düşman deler; her 4. atış dev tüy (3×)"] = "7-feather fan, pierces 2 foes; every 4th shot a giant feather (3×)",
            ["EVRİM: 7 tüylük geniş yelpaze; tüyler 2 düşmanı deler, sık sık dev tüy atar."] = "EVOLVED: a wide 7-feather fan; feathers pierce 2 foes and giant ones fly often.",
            ["Süpernova Omleti"] = "Supernova Omelette",
            ["Galaksi Girdabı"] = "Galaxy Vortex",
            ["Sakız Gezegen Halkaları"] = "Gum Planet Rings",
            ["Fırtına Kedisi Tanrıçası"] = "Storm Cat Goddess",
            ["Gökkuşağı Fırtınası"] = "Rainbow Storm",
            ["Kozmik Kahvaltı"] = "Cosmic Breakfast",
            ["Şeker Kalkanı Galaksisi"] = "Candy Shield Galaxy",
            ["Kırılan gökkuşağı lazeri"] = "A refracting rainbow laser",
            ["2 paralel tüy, hızlı atış"] = "2 parallel feathers, rapid fire",
            ["3 paralel tüy, daha hızlı"] = "3 parallel feathers, faster",
            ["3 tüy, hafif yelpaze"] = "3 feathers in a light fan",
            ["Hasar +%30, tüyler 1 düşmanı deler"] = "+30% damage, feathers pierce 1 enemy",
            ["5 tüy; her 5. atış dev tüy (3×)"] = "5 feathers; every 5th shot is a giant feather (3×)",
            ["Her 5 atışta ekranı kaplayan omlet dalgası"] = "Every 5 shots, a screen-wide omelette wave",
            ["Patlayan yumurta"] = "Exploding egg",
            ["2 yumurta"] = "2 eggs",
            ["Patlama alanı +%40"] = "+40% blast area",
            ["Patlamadan 2 mini civciv çıkar"] = "Blasts release 2 mini chicks",
            ["4 yumurta, daha sık"] = "4 eggs, more often",
            ["Düşmanları çeken galaksi sarmalı"] = "A galaxy spiral that pulls enemies in",
            ["Gidip dönen yıldız"] = "A star that flies out and back",
            ["2 yıldız"] = "2 stars",
            ["Menzil +%30, dönüşte 1.5× hasar"] = "+30% range, 1.5× damage on the return",
            ["3 yıldız"] = "3 stars",
            ["Dönen yıldızlar gemi etrafında tur atar"] = "Returning stars circle the ship",
            ["Emen, yapıştıran ve biçen 3 halka"] = "3 rings that absorb, stick and slice",
            ["Etrafında dönen 2 balon"] = "2 bubbles orbit you",
            ["3 balon"] = "3 bubbles",
            ["Balonlar düşman mermisi yutar"] = "Bubbles swallow enemy bullets",
            ["4 balon, daha geniş yörünge"] = "4 bubbles, wider orbit",
            ["Mermi yutan balon patlar"] = "A bubble that swallows a bullet bursts",
            ["Yıldırım yağmuru ve elektrikli papatyalar"] = "Lightning rain and electric daisies",
            ["Zincirleme şimşek (2 sekme)"] = "Chain lightning (2 bounces)",
            ["4 sekme"] = "4 bounces",
            ["Vurulan düşman sersemler"] = "Hit enemies are stunned",
            ["İkinci kedi"] = "A second cat",
            ["Sekmelerde hasar azalmaz"] = "No damage falloff on bounces",

            // ---- Passives
            ["Kristal Gözlük"] = "Crystal Glasses",
            ["Sıcak Tava"] = "Hot Pan",
            ["Ay Tozu"] = "Moon Dust",
            ["Esnek Sakız"] = "Stretchy Gum",
            ["Pil Tasması"] = "Battery Collar",
            ["Havuç Kalkan"] = "Carrot Shield",
            ["Mıknatıs Kulak"] = "Magnet Ears",
            ["Şans Yoncası"] = "Lucky Clover",

            // ---- Characters
            ["Pıtır"] = "Pip",
            ["Cıvık"] = "Chirpy",
            ["Mırnav"] = "Purrl",
            ["Balonbaş"] = "Bubbles",
            ["Yıldızpati"] = "Starpaw",
            ["Gökkuşağı Pıtır"] = "Rainbow Pip",
            ["Tavşan. Her 10 seviyede +1 kart seçeneği."] = "Bunny. +1 card choice every 10 levels.",
            ["Civciv. Patlamalar %20 büyük, can -%10."] = "Chick. Blasts 20% bigger, -10% HP.",
            ["Kedi. Sersemletme süresi 2 kat."] = "Cat. Stuns last twice as long.",
            ["Hamster. Yuttuğu her mermi 1 can."] = "Hamster. Every swallowed bullet heals 1 HP.",
            ["Tilki. Her evrim +%15 hasar."] = "Fox. +15% damage per evolution.",
            ["Gizli. Her koşu rastgele bir pasifle başlar."] = "Secret. Starts every run with a random passive.",

            // ---- Workshop
            ["Can"] = "Health",
            ["Hasar"] = "Damage",
            ["Atış Hızı"] = "Fire Rate",
            ["Mıknatıs"] = "Magnet",
            ["Zırh"] = "Armor",
            ["Şans"] = "Luck",
            ["Tecrübe"] = "Experience",
            ["Diriliş"] = "Revive",

            // ---- Constellation
            ["Kıvılcım"] = "Spark",
            ["Keskin Göz"] = "Sharp Eye",
            ["Alev"] = "Flame",
            ["Çevik Pati"] = "Nimble Paw",
            ["Geniş Kanat"] = "Wide Wing",
            ["Yıldız Ateşi"] = "Starfire",
            ["Rüzgâr"] = "Wind",
            ["Uzun Kuyruk"] = "Long Tail",
            ["Süpernova"] = "Supernova",
            ["Evrim Yıldızı"] = "Evolution Star",
            ["Evrim sandığı +1 pasif seviyesi verir"] = "Evolution chests grant +1 passive level",
            ["Pamuk"] = "Cotton",
            ["Kabuk"] = "Shell",
            ["Çekim"] = "Pull",
            ["Yastık"] = "Pillow",
            ["Kıl Payı"] = "Close Call",
            ["Kıl payı XP'si 2 kat"] = "Graze XP ×2",
            ["Kalp"] = "Heart",
            ["Anka"] = "Phoenix",
            ["Büyük Çekim"] = "Big Pull",
            ["Kale"] = "Fortress",
            ["Kese"] = "Pouch",
            ["Yonca"] = "Clover",
            ["Bilge"] = "Sage",
            ["Taç Avcısı"] = "Crown Hunter",
            ["Hazine"] = "Treasure",
            ["İkinci Şans"] = "Second Chance",
            ["Âlim"] = "Scholar",
            ["Seçici"] = "Picky",
            ["Define"] = "Hoard",
            ["Dördüncü Kart"] = "Fourth Card",
            ["Seviye atlamada 4 kart"] = "4 cards on level-up",

            // ---- Chapters and phases
            ["Şekerkamışı"] = "Candy Cane Lane",
            ["Jöle Nebulası"] = "Jelly Nebula",
            ["Kurabiye Kuşağı"] = "Cookie Belt",
            ["Mini-Boss: Jöle Kral!"] = "Mini-Boss: Jelly King!",
            ["Mini-Boss: Kurabiye Robot Ana!"] = "Mini-Boss: Cookie Mech Mama!",
            ["Final: Kraliçe Tavuk!"] = "Final: Queen Hen!",

            // ---- Ads
            ["Kilitli — açınca kart havuzuna girer"] = "Locked — unlocking adds it to the card pool",
            ["Sv. Atla"] = "Level Up",
            ["ATEŞ GÜCÜ"] = "FIREPOWER",
            ["ATEŞ HIZI"] = "FIRE RATE",
            ["YENİ REKOR!"] = "NEW RECORD!",
            ["Yeni Oyun"] = "New Game",
            ["sunar"] = "presents",
            ["ŞEKER HAZIR!"] = "SUGAR READY!",
            ["ANA SİLAH"] = "MAIN GUN",
            ["SİLAH"] = "WEAPON",
            ["GÜÇLENDİRME"] = "BOOST",
            ["BONUS"] = "BONUS",
            ["ŞEKER HAZIR! Bırak ve tekrar bas!"] = "SUGAR READY! Lift and press again!",
            ["Önüne düz tüy mermileri atar. Güvenilir ana silahın."] = "Fires straight feather shots ahead. Your reliable main gun.",
            ["Düşman kalabalığına patlayan yumurtalar fırlatır."] = "Lobs eggs that explode in crowds.",
            ["Gidip geri dönen yıldız; iki yönde de vurur."] = "A star that flies out and back, hitting both ways.",
            ["Geminin etrafında dönen balonlar yakındaki düşmanları ezer."] = "Bubbles orbit your ship and crush nearby foes.",
            ["Düşmandan düşmana seken zincir şimşek atar."] = "Chain lightning that jumps from foe to foe.",
            ["EVRİM: Önündeki her şeyi delen gökkuşağı lazeri (ekrandaki ışık sütunu)."] = "EVOLVED: a rainbow laser that pierces everything ahead (the column of light).",
            ["EVRİM: Dev yumurtalar ve ekranı kaplayan omlet dalgası."] = "EVOLVED: giant eggs and a screen-wide omelette wave.",
            ["EVRİM: Düşmanları içine çekip ezen galaksi girdabı."] = "EVOLVED: a vortex that pulls foes in and crushes them.",
            ["EVRİM: Mermileri emen, düşmanları biçen sakız halkaları."] = "EVOLVED: gum rings that swallow bullets and mow foes down.",
            ["EVRİM: Gökten yıldırım yağdıran kedi tanrıça."] = "EVOLVED: a cat goddess raining lightning.",
            ["FÜZYON: Prizma ışını ile fırtına kedisi tek silahta."] = "FUSION: prism beam and storm cat in one weapon.",
            ["FÜZYON: Tüy fırtınası ile fırtına kedisi tek silahta."] = "FUSION: feather storm and storm cat in one weapon.",
            ["FÜZYON: Omlet dalgası ile galaksi girdabı tek silahta."] = "FUSION: omelette wave and galaxy vortex in one weapon.",
            ["FÜZYON: Sakız halkaları ile galaksi girdabı tek silahta."] = "FUSION: gum rings and galaxy vortex in one weapon.",
            ["Kritik vuruş şansı: kritik vuruş 2 kat hasar verir."] = "Critical hit chance: crits deal double damage.",
            ["Patlama ve etki alanlarını büyütür."] = "Makes explosions and areas bigger.",
            ["Silah etkileri daha uzun sürer."] = "Weapon effects last longer.",
            ["Yörünge ve alan silahlarını genişletir."] = "Widens orbit and area weapons.",
            ["Tüm silahlar daha sık ateş eder."] = "All weapons fire more often.",
            ["Maksimum canını artırır."] = "Raises your maximum HP.",
            ["Taş ve altınları daha uzaktan çeker."] = "Pulls gems and gold from farther away.",
            ["Nadir kart ve daha iyi ödül şansı."] = "Better odds of rare cards and rewards.",
            ["BOSS"] = "BOSS",
            ["DEVAM ET"] = "CONTINUE",
            ["Kaydet ve Çık"] = "Save & Quit",
            ["Güzel uçuş!"] = "Nice flight!",
            ["Reklam hazır değil, biraz sonra dene."] = "Ad not ready, try again soon."
        };

        public static readonly Dictionary<string, string> Templates = new()
        {
            ["Sv. {0}"] = "Lv. {0}",
            ["Bölüm {0} başladı!"] = "Stage {0} begins!",
            ["Kayıt: Bölüm {0} · {1}"] = "Saved: Stage {0} · {1}",
            ["Rekor: {0}"] = "Best: {0}",
            ["BOSS  %{0}"] = "BOSS  {0}%",
            ["Seviye {0}: {1}"] = "Level {0}: {1}",
            ["EVRİM: Maks. seviye + {0} » {1}"] = "EVOLVE: max level + {0} » {1}",
            ["+%{0} {1} (toplam +%{2})"] = "+{0}% {1} (total +{2}%)",
            ["{0} evrim anahtarı"] = "Evolution key for {0}",
            ["EVRİM! {0} » {1}"] = "EVOLVED! {0} » {1}",
            ["Ustalık {0}/{1}: +%{2} hasar"] = "Mastery {0}/{1}: +{2}% damage",
            ["Kilitli: açınca oyunda kartı çıkmaya başlar"] = "Locked: unlock it to start seeing its card in runs",
            ["Şu an {0}  »  {1}"] = "Now {0}  »  {1}",
            ["Şu an {0}  ·  MAKS"] = "Now {0}  ·  MAX",
            ["+%{0}"] = "+{0}%",
            ["-{0} hasar"] = "-{0} damage",
            ["+{0} hak"] = "+{0} uses",
            ["Sv.{0}/{1}"] = "Lv.{0}/{1}",
            ["Geliştir\n{0} altın"] = "Upgrade\n{0} gold",
            ["AR-GE"] = "R&D",
            ["Ar-Ge"] = "Research",
            ["SİLAHLAR"] = "WEAPONS",
            ["Silahlar"] = "Weapons",
            ["PİLOTLAR"] = "PILOTS",
            ["Pilotlar"] = "Pilots",
            ["SALDIRI  ·  her oyunda geçerli"] = "ATTACK  ·  applies to every run",
            ["SAVUNMA"] = "DEFENCE",
            ["YARDIMCI"] = "SUPPORT",
            ["YILDIZ HARİTASI  ·  Yıldız Tozu ile"] = "STAR MAP  ·  with Stardust",
            ["Boss yendikçe Yıldız Tozu kazanırsın; özel yetenekleri burada açarsın."] = "Beating bosses earns Stardust; unlock special talents here.",
            ["Aç"] = "Open",
            ["Hemen aç"] = "Unlock now",
            ["Sv. Atla"] = "Level Up",
            ["YILDIZ HARİTASI"] = "STAR MAP",
            ["veya Bölüm {0} geçilince"] = "or clear Stage {0}",
            ["Ateş Gücü"] = "Firepower",
            ["Ateş Hızı"] = "Fire Rate",
            ["Tüm silahların ve yardımcı pilotların hasarı artar. Sınırsız."] = "All weapons and wingmen hit harder. No cap.",
            ["Tüm silahlar ve yardımcı pilotlar daha sık ateş eder."] = "All weapons and wingmen fire more often.",
            ["Oyuna daha fazla maksimum canla başlarsın."] = "Start every run with more max HP.",
            ["Aldığın her darbe biraz daha az acıtır."] = "Every hit you take hurts a little less.",
            ["Ölünce olduğun yerde dirilme hakkı (her oyun)."] = "Revive on the spot when you fall (each run).",
            ["Taşları ve altınları daha uzaktan toplarsın."] = "Collect gems and gold from farther away.",
            ["Taşlardan daha çok tecrübe: daha hızlı seviye atlarsın."] = "More XP from gems: level up faster.",
            ["Nadir ve efsanevi kartların çıkma şansı artar."] = "Better odds of rare and legendary cards.",
            ["Seviye atlayınca kartları yeniden çekme hakkı."] = "Redraw the cards when you level up.",
            ["İstemediğin bir kartı o oyundan tamamen çıkarma hakkı."] = "Remove an unwanted card from that run.",
            ["Tüm silahların hasarı artar."] = "All weapons deal more damage.",
            ["Silahlar daha sık ateş eder."] = "Weapons fire more often.",
            ["{0}\nSv.{1}  ·  {2} altın"] = "{0}\nLv.{1}  ·  {2} gold",
            ["{0}\nSv.{1}  ·  MAKS"] = "{0}\nLv.{1}  ·  MAX",
            ["{0}  YENİ!"] = "{0}  NEW!",
            ["{0}  Sv.{1}"] = "{0}  Lv.{1}",
            ["Sv.{0}"] = "Lv.{0}",
            ["Seviye {0}!"] = "Level {0}!",
            ["Seviye {0}   ·   {1} düşman   ·   {2}"] = "Level {0}   ·   {1} enemies   ·   {2}",
            ["EVRİM! {0}"] = "EVOLVED! {0}",
            ["Yeniden Çek ({0})"] = "Reroll ({0})",
            ["Yasakla ({0})"] = "Banish ({0})",
            ["Diril ({0})"] = "Revive ({0})",
            ["Evrim anahtarı: {0}"] = "Evolution key: {0}",
            ["+%{0} {1}"] = "+{0}% {1}",
            ["+{0} altın"] = "+{0} gold",
            ["+{0} Yıldız Tozu"] = "+{0} Stardust",
            ["{0} altın   ·   {1} Yıldız Tozu"] = "{0} gold   ·   {1} Stardust",
            ["{0} altın"] = "{0} gold",
            ["{0} altın\n{1} toz"] = "{0} gold\n{1} dust",
            ["{0} toz"] = "{0} dust",
            ["{0} geliştirmesi hazır!"] = "{0} upgrade ready!",
            ["{0} için {1} altın kaldı"] = "{1} gold to {0}",
            ["Bölüm {0}"] = "Stage {0}",
            ["Bölüm {0}  (kilitli)"] = "Chapter {0}  (locked)",
            ["Bölüm {0}'i bitir"] = "Clear Chapter {0}",
            ["Pilot: {0}"] = "Pilot: {0}",
            ["{0}  (silah)"] = "{0}  (weapon)",
            ["{0}  (pasif)"] = "{0}  (passive)",
            ["{0}  (açık)"] = "{0}  (owned)",
            ["{0}  {1}/{2}"] = "{0}  {1}/{2}",
            ["{0} KOMBO"] = "{0} COMBO",
            ["Filoya katıldı! ({0})"] = "Joined the fleet! ({0})",
            ["{0} + {1}"] = "{0} + {1}",
            ["<size={0}>{1}</size>"] = "<size={0}>{1}</size>",
            ["Ustalık {0}/{1}"] = "Mastery {0}/{1}",
            ["Pilot Sv. {0}/{1}  (+%{2} hasar ve can)"] = "Pilot Lv. {0}/{1}  (+{2}% damage and HP)",
            ["{0} — Dalga {1}"] = "{0} — Wave {1}",
            ["Dalga {0}: Kaos"] = "Wave {0}: Chaos",
            ["Dalga {0}"] = "Wave {0}",
            ["Alınan hasar -{0}"] = "Damage taken -{0}",
            ["Elitlerden +%{0} altın"] = "+{0}% gold from elites",
            ["+{0} diriliş"] = "+{0} revive",
            ["+{0} yeniden çek"] = "+{0} reroll",
            ["+{0} yasakla"] = "+{0} banish"
        };
    }
}
